
cargo-features = ['codegen-backend']

[profile.dev]
codegen-backend = 'cranelift'
split-debuginfo = 'unpacked'

[profile.dev.build-override]
opt-level = 3

[profile.release]
lto = true

[workspace]
resolver = '2'
members = [
	'apps/client_tauri',
	'apps/api_server',
	'libs/rs/shared',
]
