-- CreateEnum
CREATE TYPE "forza_type" AS ENUM ('FH5', 'FH4', 'FM7', 'FM8');

-- CreateEnum
CREATE TYPE "forza_car_class" AS ENUM ('D', 'C', 'B', 'A', 'S1', 'S2', 'S3', 'X');

-- CreateEnum
CREATE TYPE "forza_drive_type" AS ENUM ('FWD', 'RWD', 'AWD');

-- CreateTable
CREATE TABLE "forza_telemetry" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "game_type" "forza_type" NOT NULL,
    "is_race_on" BOOLEAN NOT NULL DEFAULT false,
    "date_time" TIMESTAMPTZ NOT NULL,
    "car_id" INTEGER NOT NULL,
    "car_class" "forza_car_class" NOT NULL,
    "car_performance_index" INTEGER NOT NULL,
    "drive_type" "forza_drive_type" NOT NULL,
    "track_id" INTEGER,
    "num_cylinders" INTEGER NOT NULL,
    "engine_max_rpm" REAL NOT NULL,
    "engine_idle_rpm" REAL NOT NULL,
    "engine_current_rpm" REAL NOT NULL,
    "acceleration_x" REAL NOT NULL,
    "acceleration_y" REAL NOT NULL,
    "acceleration_z" REAL NOT NULL,
    "velocity_x" REAL NOT NULL,
    "velocity_y" REAL NOT NULL,
    "velocity_z" REAL NOT NULL,
    "angular_velocity_x" REAL NOT NULL,
    "angular_velocity_y" REAL NOT NULL,
    "angular_velocity_z" REAL NOT NULL,
    "yaw" REAL NOT NULL,
    "pitch" REAL NOT NULL,
    "roll" REAL NOT NULL,
    "normalized_suspension_travel_front_left" REAL NOT NULL,
    "normalized_suspension_travel_front_right" REAL NOT NULL,
    "normalized_suspension_travel_rear_left" REAL NOT NULL,
    "normalized_suspension_travel_rear_right" REAL NOT NULL,
    "tire_slip_ratio_front_left" REAL NOT NULL,
    "tire_slip_ratio_front_right" REAL NOT NULL,
    "tire_slip_ratio_rear_left" REAL NOT NULL,
    "tire_slip_ratio_rear_right" REAL NOT NULL,
    "wheel_rotation_speed_front_left" REAL NOT NULL,
    "wheel_rotation_speed_front_right" REAL NOT NULL,
    "wheel_rotation_speed_rear_left" REAL NOT NULL,
    "wheel_rotation_speed_rear_right" REAL NOT NULL,
    "wheel_on_rumble_strip_front_left" BOOLEAN NOT NULL,
    "wheel_on_rumble_strip_front_right" BOOLEAN NOT NULL,
    "wheel_on_rumble_strip_rear_left" BOOLEAN NOT NULL,
    "wheel_on_rumble_strip_rear_right" BOOLEAN NOT NULL,
    "wheel_in_puddle_front_left" REAL NOT NULL,
    "wheel_in_puddle_front_right" REAL NOT NULL,
    "wheel_in_puddle_rear_left" REAL NOT NULL,
    "wheel_in_puddle_rear_right" REAL NOT NULL,
    "surface_rumble_front_left" REAL NOT NULL,
    "surface_rumble_front_right" REAL NOT NULL,
    "surface_rumble_rear_left" REAL NOT NULL,
    "surface_rumble_rear_right" REAL NOT NULL,
    "tire_slip_angle_front_left" REAL NOT NULL,
    "tire_slip_angle_front_right" REAL NOT NULL,
    "tire_slip_angle_rear_left" REAL NOT NULL,
    "tire_slip_angle_rear_right" REAL NOT NULL,
    "tire_combined_slip_front_left" REAL NOT NULL,
    "tire_combined_slip_front_right" REAL NOT NULL,
    "tire_combined_slip_rear_left" REAL NOT NULL,
    "tire_combined_slip_rear_right" REAL NOT NULL,
    "suspension_travel_meters_front_left" REAL NOT NULL,
    "suspension_travel_meters_front_right" REAL NOT NULL,
    "suspension_travel_meters_rear_left" REAL NOT NULL,
    "suspension_travel_meters_rear_right" REAL NOT NULL,
    "position_x" REAL,
    "position_y" REAL,
    "position_z" REAL,
    "speed" REAL,
    "power" REAL,
    "torque" REAL,
    "tire_temp_front_left" REAL,
    "tire_temp_front_right" REAL,
    "tire_temp_rear_left" REAL,
    "tire_temp_rear_right" REAL,
    "boost" REAL,
    "fuel" REAL,
    "distance_traveled" REAL,
    "best_lap" REAL,
    "last_lap" REAL,
    "current_lap" REAL,
    "current_race_time" REAL,
    "lap_number" INTEGER,
    "position" INTEGER,
    "acceleration" INTEGER,
    "brake" INTEGER,
    "clutch" INTEGER,
    "handbrake" INTEGER,
    "gear" INTEGER,
    "steer" INTEGER,
    "normalized_driving_lane" INTEGER,
    "normalized_ai_brake_difference" INTEGER,
    "tire_wear_front_left" REAL,
    "tire_wear_front_right" REAL,
    "tire_wear_rear_left" REAL,
    "tire_wear_rear_right" REAL,

    CONSTRAINT "forza_telemetry_user_id_game_type_date_time_pkey" PRIMARY KEY ("user_id", "game_type", "date_time"),
    CONSTRAINT "forza_telemetry_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create hypertable
SELECT create_hypertable('forza_telemetry', by_range('date_time', INTERVAL '1 hour'));



