-- CreateEnum
CREATE TYPE "forza_type" AS ENUM ('FH5', 'FH4', 'FM7', 'FM8');

-- CreateEnum
CREATE TYPE "forza_car_class" AS ENUM ('D', 'C', 'B', 'A', 'S1', 'S2', 'S3', 'X');

-- CreateEnum
CREATE TYPE "forza_drive_type" AS ENUM ('FWD', 'RWD', 'AWD');

-- CreateTable
CREATE TABLE "forza_data" (
    "id" TEXT NOT NULL,
    "game_type" "forza_type" NOT NULL,
    "is_race_on" BOOLEAN NOT NULL DEFAULT false,
    "date_time" TIMESTAMPTZ NOT NULL,
    "car_id" INTEGER NOT NULL,
    "car_class" "forza_car_class" NOT NULL,
    "car_performance_index" INTEGER NOT NULL,
    "drive_type" "forza_drive_type" NOT NULL,
    "track_id" INTEGER,
    "num_cylinders" INTEGER NOT NULL,
    "engine_max_rpm" NUMERIC NOT NULL,
    "engine_idle_rpm" NUMERIC NOT NULL,
    "engine_current_rpm" NUMERIC NOT NULL,
    "acceleration_x" NUMERIC NOT NULL,
    "acceleration_y" NUMERIC NOT NULL,
    "acceleration_z" NUMERIC NOT NULL,
    "velocity_x" NUMERIC NOT NULL,
    "velocity_y" NUMERIC NOT NULL,
    "velocity_z" NUMERIC NOT NULL,
    "angular_velocity_x" NUMERIC NOT NULL,
    "angular_velocity_y" NUMERIC NOT NULL,
    "angular_velocity_z" NUMERIC NOT NULL,
    "yaw" NUMERIC NOT NULL,
    "pitch" NUMERIC NOT NULL,
    "roll" NUMERIC NOT NULL,
    "normalized_suspension_travel_front_left" NUMERIC NOT NULL,
    "normalized_suspension_travel_front_right" NUMERIC NOT NULL,
    "normalized_suspension_travel_rear_left" NUMERIC NOT NULL,
    "normalized_suspension_travel_rear_right" NUMERIC NOT NULL,
    "tire_slip_ratio_front_left" NUMERIC NOT NULL,
    "tire_slip_ratio_front_right" NUMERIC NOT NULL,
    "tire_slip_ratio_rear_left" NUMERIC NOT NULL,
    "tire_slip_ratio_rear_right" NUMERIC NOT NULL,
    "wheel_rotation_speed_front_left" NUMERIC NOT NULL,
    "wheel_rotation_speed_front_right" NUMERIC NOT NULL,
    "wheel_rotation_speed_rear_left" NUMERIC NOT NULL,
    "wheel_rotation_speed_rear_right" NUMERIC NOT NULL,
    "wheel_on_rumble_strip_front_left" BOOLEAN NOT NULL,
    "wheel_on_rumble_strip_front_right" BOOLEAN NOT NULL,
    "wheel_on_rumble_strip_rear_left" BOOLEAN NOT NULL,
    "wheel_on_rumble_strip_rear_right" BOOLEAN NOT NULL,
    "wheel_in_puddle_front_left" NUMERIC NOT NULL,
    "wheel_in_puddle_front_right" NUMERIC NOT NULL,
    "wheel_in_puddle_rear_left" NUMERIC NOT NULL,
    "wheel_in_puddle_rear_right" NUMERIC NOT NULL,
    "surface_rumble_front_left" NUMERIC NOT NULL,
    "surface_rumble_front_right" NUMERIC NOT NULL,
    "surface_rumble_rear_left" NUMERIC NOT NULL,
    "surface_rumble_rear_right" NUMERIC NOT NULL,
    "tire_slip_angle_front_left" NUMERIC NOT NULL,
    "tire_slip_angle_front_right" NUMERIC NOT NULL,
    "tire_slip_angle_rear_left" NUMERIC NOT NULL,
    "tire_slip_angle_rear_right" NUMERIC NOT NULL,
    "tire_combined_slip_front_left" NUMERIC NOT NULL,
    "tire_combined_slip_front_right" NUMERIC NOT NULL,
    "tire_combined_slip_rear_left" NUMERIC NOT NULL,
    "tire_combined_slip_rear_right" NUMERIC NOT NULL,
    "suspension_travel_meters_front_left" NUMERIC NOT NULL,
    "suspension_travel_meters_front_right" NUMERIC NOT NULL,
    "suspension_travel_meters_rear_left" NUMERIC NOT NULL,
    "suspension_travel_meters_rear_right" NUMERIC NOT NULL,
    "position_x" NUMERIC,
    "position_y" NUMERIC,
    "position_z" NUMERIC,
    "speed" NUMERIC,
    "power" NUMERIC,
    "torque" NUMERIC,
    "tire_temp_front_left" NUMERIC,
    "tire_temp_front_right" NUMERIC,
    "tire_temp_rear_left" NUMERIC,
    "tire_temp_rear_right" NUMERIC,
    "boost" NUMERIC,
    "fuel" NUMERIC,
    "distance_traveled" NUMERIC,
    "best_lap" NUMERIC,
    "last_lap" NUMERIC,
    "current_lap" NUMERIC,
    "current_race_time" NUMERIC,
    "lap_number" INTEGER,
    "position" INTEGER,
    "acceleration" INTEGER,
    "brake" INTEGER,
    "clutch" INTEGER,
    "handbrake" INTEGER,
    "gear" INTEGER,
    "steer" INTEGER,
    "normalized_driving_lane" INTEGER,
    "normalized_ai_brake_difference" INTEGER,
    "tire_wear_front_left" NUMERIC,
    "tire_wear_front_right" NUMERIC,
    "tire_wear_rear_left" NUMERIC,
    "tire_wear_rear_right" NUMERIC,

    CONSTRAINT "forza_data_pkey" PRIMARY KEY ("id")
);
